# Generated by Django 5.1.3 on 2024-12-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationapp', '0002_alter_destination_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='Images',
            field=models.ImageField(upload_to='images'),
        ),
    ]
