# Generated by Django 5.1.3 on 2024-12-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationapp', '0003_alter_destination_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='Images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
