# Generated by Django 5.1.3 on 2024-12-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationapp', '0005_remove_destination_images_destinationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='Images',
            field=models.ImageField(default=1234, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DestinationImage',
        ),
    ]
